# 1.) Load the data in the file iris.data in a 2-D array called iris

In [1]:
import numpy as np
iris=np.loadtxt('iris.data',delimiter=',',dtype=str)
print(iris)


[['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['5.4' '3.4' '1.7' '0.2' 'Iris-setosa']
 ['5.1' '3.7' '1.5' '0.4' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['5.1' '3.3' '1.7' '0.5' 'Iris-setosa']
 ['4.8' '3.4' '1

# 2.)Drop the column whose index=4 from the array iris

In [2]:
temp=np.delete(iris,4,1)
print(temp)

[['5.1' '3.5' '1.4' '0.2']
 ['4.9' '3.0' '1.4' '0.2']
 ['4.7' '3.2' '1.3' '0.2']
 ['4.6' '3.1' '1.5' '0.2']
 ['5.0' '3.6' '1.4' '0.2']
 ['5.4' '3.9' '1.7' '0.4']
 ['4.6' '3.4' '1.4' '0.3']
 ['5.0' '3.4' '1.5' '0.2']
 ['4.4' '2.9' '1.4' '0.2']
 ['4.9' '3.1' '1.5' '0.1']
 ['5.4' '3.7' '1.5' '0.2']
 ['4.8' '3.4' '1.6' '0.2']
 ['4.8' '3.0' '1.4' '0.1']
 ['4.3' '3.0' '1.1' '0.1']
 ['5.8' '4.0' '1.2' '0.2']
 ['5.7' '4.4' '1.5' '0.4']
 ['5.4' '3.9' '1.3' '0.4']
 ['5.1' '3.5' '1.4' '0.3']
 ['5.7' '3.8' '1.7' '0.3']
 ['5.1' '3.8' '1.5' '0.3']
 ['5.4' '3.4' '1.7' '0.2']
 ['5.1' '3.7' '1.5' '0.4']
 ['4.6' '3.6' '1.0' '0.2']
 ['5.1' '3.3' '1.7' '0.5']
 ['4.8' '3.4' '1.9' '0.2']
 ['5.0' '3.0' '1.6' '0.2']
 ['5.0' '3.4' '1.6' '0.4']
 ['5.2' '3.5' '1.5' '0.2']
 ['5.2' '3.4' '1.4' '0.2']
 ['4.7' '3.2' '1.6' '0.2']
 ['4.8' '3.1' '1.6' '0.2']
 ['5.4' '3.4' '1.5' '0.4']
 ['5.2' '4.1' '1.5' '0.1']
 ['5.5' '4.2' '1.4' '0.2']
 ['4.9' '3.1' '1.5' '0.1']
 ['5.0' '3.2' '1.2' '0.2']
 ['5.5' '3.5' '1.3' '0.2']
 

# 3.)Display the shape, dimensions and size of iris

In [3]:
print('Iris shape:',np.shape(iris))
print('Iris Dimensions:',iris.ndim)
print('Iris Size',iris.size)

Iris shape: (150, 5)
Iris Dimensions: 2
Iris Size 750


# 4.)Split iris into 3 2-D arrays, each array for a different species and call them iris1,iris2,iris3

In [5]:
idx1=iris[:,-1]=='Iris-setosa'
idx2=iris[:,-1]=='Iris-virginica'
idx3=iris[:,-1]=='Iris-versicolor'
iris=np.delete(iris,4,axis=1)
iris=iris.astype(float)
iris1=iris[idx1]
iris2=iris[idx2]
iris3=iris[idx3]

# 5.)Print the three arrays iris1, iris2 and iris3

In [6]:
print('Iris 1:\n',iris1,'\n\nIris2:\n',iris2,'\n\nIris3:\n',iris3)


Iris 1:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]] 

Iris2:
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5

# 6.)Create a 1-D array header having elements "sepal length", "sepal width", "petal length", "petal width", "species no" in that order

In [11]:
irisd=np.loadtxt('iris.data',delimiter=',',dtype=str)
irisd=np.array(np.insert(irisd,0,np.array(["sepal length", "sepal width", "petal length", "petal width", "species no"]),axis=0))

# 7.)Display the array header

In [12]:
print(irisd)

[['sepal length' 'sepal width' 'petal length' 'petal width' 'species no']
 ['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['5.4' '3.4' '1.7' '0.2' 'Iris-setosa']
 ['5.1' '3.7' '1.5' '0.4' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2

# 8.)Find the max,min,mean and standard deviation for the columns of the iris  and the store the results in the arrays iris_max,iris_min,iris_avg,iris_std,iris_var respectively.The results must be rounded to not more than 2 decimal places

In [15]:
iris=iris.astype(float)
iris_max=np.round(np.max(iris,axis=0),2)
iris_min=np.round(np.min(iris,axis=0),2)
iris_avg=np.round(np.average(iris,axis=0),2)
iris_std=np.round(np.std(iris,axis=0),2)
iris_var=np.round(np.var(iris,axis=0),2)

# 9.)Similarly find the max,min,mean and standard deviationfor the columns of iris1,iris2,iris3 and store the results in the arrays with appropriate names

In [17]:
iris1_max=np.round(np.max(iris1,axis=0),2)
iris1_min=np.round(np.min(iris1,axis=0),2)
iris1_avg=np.round(np.average(iris1,axis=0),2)
iris1_std=np.round(np.std(iris1,axis=0),2)
iris1_var=np.round(np.var(iris1,axis=0),2)

iris2_max=np.round(np.max(iris2,axis=0),2)
iris2_min=np.round(np.min(iris2,axis=0),2)
iris2_avg=np.round(np.average(iris2,axis=0),2)
iris2_std=np.round(np.std(iris2,axis=0),2)
iris2_var=np.round(np.var(iris2,axis=0),2)

iris3_max=np.round(np.max(iris3,axis=0),2)
iris3_min=np.round(np.min(iris3,axis=0),2)
iris3_avg=np.round(np.average(iris3,axis=0),2)
iris3_std=np.round(np.std(iris3,axis=0),2)
iris3_var=np.round(np.var(iris3,axis=0),2)

# 10.)Comparisions of minimums

In [24]:
import pandas as pd
d={
    'Iris Setosa': np.transpose(iris_min<iris1_min),
    'Iris Virginica':np.transpose(iris_min<iris2_min),
    'Iris Versicolor':np.transpose(iris_min<iris3_min)
}
df=pd.DataFrame(d)
df.index=['Sepal Length','Sepal Width','Petal Length','Petal Width']
display(df)

Iris Setosa  Iris Virginica  Iris Versicolor
Sepal Length        False            True             True
Sepal Width          True            True            False
Petal Length        False            True             True
Petal Width         False            True             True

# 11.)Compare Iris Setosa's average sepal width to that of Iris Virginica

In [30]:
print('Iris Setosa average sepal width is greater to that of Iris Virginica:',iris1_avg[1]>iris2_avg[1])

Iris Setosa average sepal width is greater to that of Iris Virginica: True


# 12.)Compare Iris Setosa's average petal length to that of Iris Virginica

In [33]:
print('Iris Setosa average petal length is greater to that of Iris Virginica:',iris1_avg[2]>iris2_avg[2])

Iris Setosa average petal length is greater to that of Iris Virginica: False


# 13.)Compare Iris Setosa's average petal width to that of Iris Virginica

In [34]:
print('Iris Setosa average petal width is greater to that of Iris Virginica:',iris1_avg[3]>iris2_avg[3])

Iris Setosa average petal width is greater to that of Iris Virginica: False


# 14.)Save the iris_avg,iris_min,iris_max in a comma seperated file named IrisStat.txt on the hard disc

In [36]:
data=np.array([iris_avg,iris_min,iris_max])
np.savetxt('IrisStat.txt',data,delimiter=",",fmt='%.2f')