# NUMPY BASICS

In [2]:
import numpy as np
a=np.array([int(x) for x in input("Enter Elements into the array:").split()])
print('The Given array is:',a)

Enter Elements into the array:1 2 3 4
The Given array is: [1 2 3 4]


In [3]:
#sorting the array
a=np.sort(a)
print('Given Array after sorting:',a)

Given Array after sorting: [1 2 3 4]


In [24]:
#n-dimentional array filled with zeros
n=int(input('Enter the dimention:'))
a=np.zeros(n,dtype=int)
print(f"{n}-dimentional array filled with zeros is {a}")

Enter the dimention:5
5-dimentional array filled with zeros is [0 0 0 0 0]


In [28]:
#n-dimentional array filled with given number
n=int(input('Enter the dimention:'))
num=int(input('Enter the number:'))
a=np.full(n,num)
print(f"{n}-dimentional array filled with {num} is {a}")

Enter the dimention:5
Enter the number:2
5-dimentional array filled with 2 is [2 2 2 2 2]


In [34]:
#m*n-matrix filled with zeros
m=int(input('Enter m:'))
n=int(input('Enter n:'))
a=np.zeros((m,n),dtype=int)
print(f'{m}*{n}-matrix filled with zeros is \n{a}')

Enter m:3
Enter n:3
3*3-matrix filled with zeros is 
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [35]:
#m*n-matrix filled with given number
m=int(input('Enter m:'))
n=int(input('Enter n:'))
num=int(input('Enter a number:'))
a=np.full((m,n),num)
print(f'{m}*{n}-matrix filled with {num} is \n{a}')

Enter m:3
Enter n:3
Enter a number:5
3*3-matrix filled with 5 is 
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [37]:
#identity matrix of given size
m=int(input('Enter m:'))
n=int(input('Enter n:'))
a=np.eye(m,n,dtype=int)
print(f'{m}*{n} Identiti matrix is \n{a}')

Enter m:3
Enter n:3
3*3 Identiti matrix is 
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [4]:
a2=np.arange(10,50,10)
a2

array([10, 20, 30, 40])

In [8]:
a3=np.arange(2,5)
a3

array([2, 3, 4])

In [23]:
a=np.linspace(0,10,5)
print(a)


[ 0.   2.5  5.   7.5 10. ]


In [36]:
#uniformly distrbuted random values
a=np.random.random((2,2))
print(a)

[[0.7342333  0.10969849]
 [0.31882911 0.2584195 ]]


# 1.) Create a one-dimensional array and perform  all operations on it.

In [45]:
import numpy as np
a=np.array([float(x) for x in input('Enter elements into 1st array:').split()])
b=np.array([float(x) for x in input('Enter elements into 2nd array:').split()])
print('First array is:\na=',a)
print('Second array is:\nb=',b)
print('Operations on the given arrays:')
print('a+b=',a+b)
print('a-b=',a-b)
print('a*b=',a*b)
print('a/b=',a/b)
print('Square of a=',np.square(a),'\nSquare of b=',np.square(b))
print('Square root of a=',np.sqrt(a),'\nSquare root of b=',np.sqrt(b))

Enter elements into 1st array:1 2 3 4
Enter elements into 2nd array:9 8 7 6
First array is:
a= [1. 2. 3. 4.]
Second array is:
b= [9. 8. 7. 6.]
Operations on the given arrays:
a+b= [10. 10. 10. 10.]
a-b= [-8. -6. -4. -2.]
a*b= [ 9. 16. 21. 24.]
a/b= [0.11111111 0.25       0.42857143 0.66666667]
Square of a= [ 1.  4.  9. 16.] 
Square of b= [81. 64. 49. 36.]
Square root of a= [1.         1.41421356 1.73205081 2.        ] 
Square root of b= [3.         2.82842712 2.64575131 2.44948974]


# 2.)	Create multi-dimensional arrays and find its shape and dimension 

In [55]:
import numpy as np
a=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
print('The Multi-dimentional array is:\n',a)
print('Dimension of a is ',a.ndim)
print('Shape of a is ',a.shape)

The Multi-dimentional array is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of a is  2
Shape of a is  (3, 3)


# iii)	Create a matrix full of zeros and ones

In [57]:
import numpy as np
m=int(input('Enter m:'))
n=int(input('Enter n:'))
a=np.eye(m,n,dtype=int)
print(f'{m}*{n} matrix full of zeros and ones is\n{a}')

Enter m:3
Enter n:3
3*3 matrix full of zeros and ones is
[[1 0 0]
 [0 1 0]
 [0 0 1]]


# iv)	Reshape and flatten data in the array

In [63]:
a=np.array([float(x) for x in input('Enter elements into the array:').split()])
m=int(input('Enter m:'))
n=int(input('Enter n:'))
print('Array before Reshape is\n',a)
a=a.reshape(m,n)
print(f'Array after Reshaping into {m}*{n} matrix is\n{a}')
a=a.flatten()
print('Array after flattening is\n',a)

Enter elements into the array:1 2 3 4 5 6
Enter m:2
Enter n:3
Array before Reshape is
 [1. 2. 3. 4. 5. 6.]
Array after Reshaping into 2*3 matrix is
[[1. 2. 3.]
 [4. 5. 6.]]
Array after flattening is
 [1. 2. 3. 4. 5. 6.]


# v)	Perform arithmetic operations on multi-dimensional  arrays

In [62]:
import numpy as np
a=np.array([[10,20,30],
           [40,50,60],
           [70,80,90]])
print("The Multi-dimentional array is:\na=",a)
print('Arithematic Operations on a:')
print('*a+10:\n',a+10,'\n*a-10:\n',a-10,'\n*a*2:\n',a*2,'\n*a/10:\n',a/10)

The Multi-dimentional array is:
a= [[10 20 30]
 [40 50 60]
 [70 80 90]]
Arithematic Operations on a:
*a+10:
 [[ 20  30  40]
 [ 50  60  70]
 [ 80  90 100]] 
*a-10:
 [[ 0 10 20]
 [30 40 50]
 [60 70 80]] 
*a*2:
 [[ 20  40  60]
 [ 80 100 120]
 [140 160 180]] 
*a/10:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# vi)	Append data vertically and horizontally 

In [1]:
import numpy as np
a=np.array([float(x) for x in input('Enter elements into the array:').split()])
print('The Given array is:\n',a)
b=([float(x) for x in input("Enter elements to append the data horizontally:").split()])
a=np.hstack((a,b))
print('Array after appending the given data horizontally is:\n',a)
c=([float(x) for x in input("Enter ",len(a),"elements to append the data vertically:").split()])
a=np.vstack((a,c))
print('Array after appending the given data vertically is:\n',a)

Enter elements into the array:1 2 3 
The Given array is:
 [1. 2. 3.]
Enter elements to append the data horizontally:4
Array after appending the given data horizontally is:
 [1. 2. 3. 4.]


TypeError: Kernel.raw_input() takes from 1 to 2 positional arguments but 4 were given