# i.) Create a one-dimensional array and perform  all operations on it.

In [45]:
import numpy as np
a=np.array([float(x) for x in input('Enter elements into 1st array:').split()])
b=np.array([float(x) for x in input('Enter elements into 2nd array:').split()])
print('First array is:\na=',a)
print('Second array is:\nb=',b)
print('Operations on the given arrays:')
print('a+b=',a+b)
print('a-b=',a-b)
print('a*b=',a*b)
print('a/b=',a/b)
print('Square of a=',np.square(a),'\nSquare of b=',np.square(b))
print('Square root of a=',np.sqrt(a),'\nSquare root of b=',np.sqrt(b))

Enter elements into 1st array:1 2 3 4
Enter elements into 2nd array:9 8 7 6
First array is:
a= [1. 2. 3. 4.]
Second array is:
b= [9. 8. 7. 6.]
Operations on the given arrays:
a+b= [10. 10. 10. 10.]
a-b= [-8. -6. -4. -2.]
a*b= [ 9. 16. 21. 24.]
a/b= [0.11111111 0.25       0.42857143 0.66666667]
Square of a= [ 1.  4.  9. 16.] 
Square of b= [81. 64. 49. 36.]
Square root of a= [1.         1.41421356 1.73205081 2.        ] 
Square root of b= [3.         2.82842712 2.64575131 2.44948974]


# ii.)	Create multi-dimensional arrays and find its shape and dimension 

In [55]:
import numpy as np
a=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
print('The Multi-dimentional array is:\n',a)
print('Dimension of a is ',a.ndim)
print('Shape of a is ',a.shape)

The Multi-dimentional array is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of a is  2
Shape of a is  (3, 3)


# iii)	Create a matrix full of zeros and ones

In [57]:
import numpy as np
m=int(input('Enter m:'))
n=int(input('Enter n:'))
a=np.eye(m,n,dtype=int)
print(f'{m}*{n} matrix full of zeros and ones is\n{a}')

Enter m:3
Enter n:3
3*3 matrix full of zeros and ones is
[[1 0 0]
 [0 1 0]
 [0 0 1]]


# iv)	Reshape and flatten data in the array

In [63]:
a=np.array([float(x) for x in input('Enter elements into the array:').split()])
m=int(input('Enter m:'))
n=int(input('Enter n:'))
print('Array before Reshape is\n',a)
a=a.reshape(m,n)
print(f'Array after Reshaping into {m}*{n} matrix is\n{a}')
a=a.flatten()
print('Array after flattening is\n',a)

Enter elements into the array:1 2 3 4 5 6
Enter m:2
Enter n:3
Array before Reshape is
 [1. 2. 3. 4. 5. 6.]
Array after Reshaping into 2*3 matrix is
[[1. 2. 3.]
 [4. 5. 6.]]
Array after flattening is
 [1. 2. 3. 4. 5. 6.]


# v)	Perform arithmetic operations on multi-dimensional  arrays

In [62]:
import numpy as np
a=np.array([[10,20,30],
           [40,50,60],
           [70,80,90]])
print("The Multi-dimentional array is:\na=",a)
print('Arithematic Operations on a:')
print('*a+10:\n',a+10,'\n*a-10:\n',a-10,'\n*a*2:\n',a*2,'\n*a/10:\n',a/10)

The Multi-dimentional array is:
a= [[10 20 30]
 [40 50 60]
 [70 80 90]]
Arithematic Operations on a:
*a+10:
 [[ 20  30  40]
 [ 50  60  70]
 [ 80  90 100]] 
*a-10:
 [[ 0 10 20]
 [30 40 50]
 [60 70 80]] 
*a*2:
 [[ 20  40  60]
 [ 80 100 120]
 [140 160 180]] 
*a/10:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# vi)	Append data vertically and horizontally 

In [11]:
import numpy as np
a=np.array([float(x) for x in input('Enter elements into the array:').split()])
print('The Given array is:\n',a)
b=([float(x) for x in input("Enter elements to append the data horizontally:").split()])
a=np.hstack((a,b))
print('Array after appending the given data horizontally is:\n',a)
c=([float(x) for x in input(f"Enter {len(a)} elements to append the data vertically:").split()])
a=np.vstack((a,c))
print('Array after appending the given data vertically is:\n',a)

Enter elements into the array:1 2
The Given array is:
 [1. 2.]
Enter elements to append the data horizontally:3 4
Array after appending the given data horizontally is:
 [1. 2. 3. 4.]
Enter 4 elements to append the data vertically:5 6 7 8
Array after appending the given data vertically is:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


# vii)	Apply indexing and slicing on array 

In [17]:
import numpy as np
a=np.array([float(x) for x in input('Enter elements into the array:').split()])
print('The Given array is:\n',a)
p=int(input('Enter a position to gets its element:'))
if(p>len(a)):
    print('Given position is out of bounds')
else:
    print(f"The element at position{p} in the array is:{a[p-1]}")

l=[int(x) for x in input('Enter a starting and ending position in the array to retrieve the elements between them:').split()]
if l[0]<0 and l[1]>len(a):
    print('Given positons are out of bounds')
else:
    print(f'The elements in the array between position{l[0]} and position{l[1]} are {a[l[0]:l[1]-1]}')

Enter elements into the array:1 2 3 4 5 6 7 8 9 0
The Given array is:
 [1. 2. 3. 4. 5. 6. 7. 8. 9. 0.]
Enter a position to gets its element:4
The element at position4 in the array is:4.0
Enter a starting and ending position in the array to retrieve the elements between them:4 8
The elements in the array between position4 and position8 are [5. 6. 7.]


# viii)	Use statistical functions on array - Min, Max, Mean, Median and Standard Deviation 

In [20]:
import numpy as np
a=np.array([float(x) for x in input('Enter elements into the array:').split()])
print('The Given array is:\n',a)
print('Minimum in a is ',np.min(a))
print('Maximum in a is ',np.max(a))
print('Mean of a is ',np.mean(a))
print('Median of a is ',np.median(a))
print('Standard Deviation of a is ',round(np.std(a),2))

Enter elements into the array:1 5 6 9 4
The Given array is:
 [1. 5. 6. 9. 4.]
Minimum in a is  1.0
Maximum in a is  9.0
Mean of a is  5.0
Median of a is  5.0
Standard Deviation of a is  2.61


# ix)	Dot  matrix product of two arrays 

In [28]:
a=[[1,2],
  [3,4]]
b=[[5,6],
  [7,8]]
print(f'Dot product of \n{a} and {b} is:\n\n{np.dot(a,b)}')

Dot product of 
[[1, 2], [3, 4]] and [[5, 6], [7, 8]] is:

[[19 22]
 [43 50]]


# x)	Compute the Eigen values of a matrix 

In [39]:
a=np.array([[3,1,1],
   [2,4,2],
   [1,1,3]])
e,v=np.linalg.eig(a)
print(f'The Eigen values of the array matrix\n{a}\nare {e}')


The Eigen values of the array matrix
[[3 1 1]
 [2 4 2]
 [1 1 3]]
are [2. 6. 2.]


# xi)	Solve a linear matrix equation such as 3 * x0 + x1 = 9, x0 + 2 * x1 = 8 

In [41]:
a=np.array([[3,1],[1,2]])
b=np.array([9,8])
x=np.linalg.solve(a,b)
print('By solving the below equations:\n3*x0+x1=9 and\nx0+2*x1=8 we get x0=',x[0],' and x1=',x[1])

By solving the below equations:
3*x0+x1=9 and
x0+2*x1=8 we get x0= 2.0  and x1= 3.0


# xii)	Compute the multiplicative inverse of a matrix 

In [44]:
a=np.array([[3,1,1],
   [2,4,2],
   [1,1,3]])
print(f'Multiplicative Inverse of matrix:\n{a} is \n{np.round(np.linalg.inv(a),2)}')

Multiplicative Inverse of matrix:
[[3 1 1]
 [2 4 2]
 [1 1 3]] is 
[[ 0.42 -0.08 -0.08]
 [-0.17  0.33 -0.17]
 [-0.08 -0.08  0.42]]


# xiii)	Compute the rank of a matrix 

In [46]:
a=np.array([[1,2,3],
   [2,3,4],
   [3,5,7]])
print(f'The rank of the matrix:\n{a} is {np.linalg.matrix_rank(a)}')

The rank of the matrix:
[[1 2 3]
 [2 3 4]
 [3 5 7]] is 2


# xiv)Compute the determinant of an array

In [48]:
a=np.array([[3,1,1],
   [2,4,2],
   [1,1,3]])
print(f'The determinant of the matrix:\n{a} is {np.round(np.linalg.det(a),2)}')

The determinant of the matrix:
[[3 1 1]
 [2 4 2]
 [1 1 3]] is 24.0


# xv)	Perform transpose and change of axes operations on arrays.

In [51]:
a=np.array([[3,1,1],
   [2,4,2],
   [1,1,3]])
print('The given matrix is:\n',a)
print('Transpose of matrix a (using transpose() method) is:\n',np.transpose(a))
print('Transpose of matrix a (using swapaxes() method) is:\n',np.swapaxes(a,0,1))

The given matrix is:
 [[3 1 1]
 [2 4 2]
 [1 1 3]]
Transpose of matrix a (using transpose() method) is:
 [[3 2 1]
 [1 4 1]
 [1 2 3]]
Transpose of matrix a (using swapaxes() method) is:
 [[3 2 1]
 [1 4 1]
 [1 2 3]]


# xvi)	Perform splitting operations on arrays.

In [62]:
arr = np.arange(9).reshape(3, 3)
print("Array:")
print(arr)
print()

print("Horizontal split:")
a,b,c = np.hsplit(arr, 3)
# a,b,c = np.split(arr,3,0)
print(a)
print(b)
print(c)
print()

print("Vertical split:")
a,b,c = np.vsplit(arr, 3)
# a,b,c = np.split(arr,3,1)
print(a)
print(b)
print(c)
print()


Array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Horizontal split:
[[0]
 [3]
 [6]]
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]

Vertical split:
[[0 1 2]]
[[3 4 5]]
[[6 7 8]]

